{{ range $user := until (int .Values.users) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.org/websocket-services: frontend{{ $user }}
  name: ing-{{ $user }}
  namespace: workshop
spec:
  rules:
  - host: user{{ $user }}.{{ $.Values.dns }}
    http:
      paths:
      - backend:
          serviceName: frontend{{ $user }}
          servicePort: 8080
{{ end }}