{{ range $user := until (int .Values.users) }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.org/websocket-services: frontend{{ $user }}
  name: ing-{{ $user }}
  namespace: workshop
spec:
  tls:
  - secretName: user{{ $user }}-tls
    hosts:
    - user{{ $user }}.{{ $.Values.dns }}
  rules:
  - host: user{{ $user }}.{{ $.Values.dns }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: frontend{{ $user }}
            port:
              number: 8080
{{ end }}