---
# all pod in workshop ns shoud be able to get the sshfront svc NodePort
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sshreader
  namespace: workshop
rules:
- apiGroups:
  - ""
  resourceNames:
  - sshfront
  resources:
  - services
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crb-sshreader
  namespace: workshop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sshreader
subjects:
{{ range $user := until (int .Values.users) }}
- kind: ServiceAccount
  name: sa-user{{ $user }}
  namespace: workshop
{{end}}