{{ range $user := until (int .Values.users) }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend{{ $user }}
  namespace: workshop
  labels:
    user: user{{ $user }}
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user{{ $user }}
{{ end }}